### PR TITLE
Add workflows and fix grammar issues

### PR DESCRIPTION
**Pull request by Jerry-py**

### CODE REVIEW

**Review by andrewthederp — CHANGES_REQUESTED** [review]
The changes in two408.py and words.txt are wrong, should not change it from `ans` to `and` and words.txt contains a bunch of wrong corrections

**Review by Jerry-py — COMMENTED** [review]
Fixed

**Review by andrewthederp — CHANGES_REQUESTED** [review]
Changes in words.txt like `cant` -> `can't` should not be seeing as words.txt is used for hangman which does not accept special characters

**Comment by Jerry-py** [comment]
Ok will revert

**Review by andrewthederp — APPROVED** [review]

**Review by andrewthederp — APPROVED** [review]

**Pull request merged**
